config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => "home#index"
	namespace :admin do
		devise_for :admin_users, class_name: "Admin::AdminUser",
		:controllers => { :registrations => 'admin/admin_users/registrations', :sessions => 'admin/admin_users/sessions', :passwords => 'admin/admin_users/passwords' },
		path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
		root :to => "/admin/dashboard#index"
		
		resources :cie_roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :cie_users do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :parameters
	end
	namespace :registry do
		devise_for :cie_users, class_name: "Registry::CieUser",
		:controllers => { :registrations => 'registry/cie_users/registrations', :sessions => 'registry/cie_users/sessions', :passwords => 'registry/cie_users/passwords' },
		path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
		root :to => "/registry/dashboard#index"
		resources :events do
			collection do
				delete 'destroy_multiple'
				get 'load_therapy_room'
			end
		end
		resources :levels do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :age_ranges do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :employees do
			collection do
				get 'load_boss'
				delete 'destroy_multiple'
			end
		end
		resources :employee_positions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_rooms do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_types do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients do
			collection do
				delete 'destroy_multiple'
				get 'load_municipalities'
				get :print_invoice, defaults: { format: 'pdf' }
			end
		end
		resources :therapy_groups do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients, param: :id do
			get 'date_schedule'
			get 'medical_record'
			post 'medical_record'
			get :assistance
			get :print_assistance, defaults: { format: 'pdf' }
			get :new_assistance_registration
			post :new_assistance_registration
		end
		resources :patients, param: :"id/:assistance_id" do
			get :edit_assistance_registration
			post :edit_assistance_registration
			delete :destroy_assistance
		end
		resources :conditions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :date_events
		resource :reports do
			get :group_week_events
			get :employee_month_events
			get :employee_week_events
			get :patient_week_events
			get :room_week_events
			get :group_week_hours
			get :group_week_covered_hours
			get :colaborador_month_covered_hours
			get :print_report, defaults: { format: 'pdf' }
		end
	end
end

app/models/registry.rb
module Registry
  def self.table_name_prefix
    'registry_'
  end
end

app/models/registry/age_range.rb
class Registry::AgeRange < ApplicationRecord
	before_destroy :check_for_level

	has_many :registry_levels, :class_name => "Registry::Level", 
		foreign_key: "facturacion_age_range_id", :inverse_of => :registry_age_range

	include AvoidDestroyReferencesUtility 

	def self.security_name
		"Rangos de Edad"
	end

	def display_name
		"#{name} (#{min_age} - #{max_age}) años"
	end

	validates_presence_of :name, :description, :max_age, :min_age
	validates_numericality_of :max_age, :min_age

	private
	def check_for_level
		check_for_relation(registry_levels, "Área")
	end
end

app/models/registry/cie_user.rb
class Registry::CieUser < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	
  	has_and_belongs_to_many :admin_cie_roles, :class_name => "Admin::CieRole",
  		:join_table => :registry_cie_users_registry_cie_roles, foreign_key: "registry_cie_user_id",
  		association_foreign_key: "admin_cie_role_id"

    validates_presence_of :admin_cie_roles
    validates_uniqueness_of :email
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	include UserModelUtility
	def self.security_name
		"Usuario de Registro"
	end

  def display_name
    self.name
  end
end

app/models/registry/condition.rb
class Registry::Condition < ApplicationRecord
	before_destroy :check_for_patient

	validates_presence_of :name, :description

	has_many :registry_patients, :class_name => "Registry::Patient", 
		foreign_key: "registry_condition_id", :inverse_of => :registry_condition

	include AvoidDestroyReferencesUtility 
	def self.security_name
		"Condición"
	end
	def display_name
		name
	end

	private
	def check_for_patient
		check_for_relation(registry_patients, "Paciente")
	end
end

app/models/registry/date_event.rb
class Registry::DateEvent < ApplicationRecord
	attr_accessor :date_range

	has_many :registry_date_event_employees, :class_name => "Registry::DateEventEmployee", 
		foreign_key: "registry_date_event_id", :inverse_of => :registry_date_event, :dependent => :destroy

	has_many :registry_employees, :through => :registry_date_event_employees, 
		:class_name => "Registry::Employee", :inverse_of => :registry_date_event

	belongs_to :registry_patient, :class_name => "Registry::Patient", :inverse_of => :registry_date_events
	
	accepts_nested_attributes_for :registry_date_event_employees,
		:allow_destroy => true,
		:reject_if     => :all_blank
		
	def color_map 
		[
			["Plata","#efefef"],
			["Gris","#c4c4c4"],
			["Negro","#000000"],
			["Marrón","#f1e3d1"],
			["Amarillo","#fffcdb"],
			["Oliva","#d9d9b2"],
			["Lima","#b2ffb2"],
			["Verde","#b2d9b2"],
			["Aqua","#ccffff"],
			["Verde Azulado","#b6daff"],
			["Azul","#0c84ff"],
			["Fucsia","#e0b6ea"],
			["Púrpura","#7300a9"],	
			['Rojo','#ffcccc'], 
			['Naranja','#ff7e00'], 
			['Cyan','#ccebf8'], 
			['Rosado','#f95aff'],
		]
	end

	def text_color_hash
		{
			"#efefef"=>"#878787",
			"#c4c4c4"=>"#888888",
			"#000000"=>"#4e4e4e",
			"#f1e3d1"=>"#ea6666",
			"#fffcdb"=>"#be8e50",
			"#d9d9b2"=>"#cdb200",
			"#b2ffb2"=>"#7e7e21",
			"#b2d9b2"=>"#629f62",
			"#ccffff"=>"#4f954f",
			"#b6daff"=>"#229c9c",
			"#0c84ff"=>"#c0c0ef",
			"#e0b6ea"=>"#6d1f81",
			"#7300a9"=>"#6f09b6",	
			'#ffcccc'=>"#b14f4f", 
			'#ff7e00'=>"#c37f3d", 
			'#ccebf8'=>"#009bdb", 
			'#f95aff'=>"#db4ac8",
		}
	end

	def start_time_formatted
		start_time.strftime("%d/%m/%Y %T")
	end

	def self.security_name
		"Citas"
	end
	def display_name
		name
	end

	def event_type_map 
		[['Cita','Cita'], ['Evaluación','Evaluación']]
	end
  	
  	def all_day_event?
  		self.end_time = self.end_time.present? ? self.end_time : self.start_time.midnight
    	self.start_time == self.start_time.midnight && self.end_time.present? && self.end_time == self.end_time.midnight ? true : false
	end
end

app/models/registry/date_event_employee.rb
class Registry::DateEventEmployee < ApplicationRecord
  belongs_to :registry_date_event, :class_name => "Registry::DateEvent", :inverse_of => :registry_date_event_employees
  belongs_to :registry_employee, :class_name => "Registry::Employee", :inverse_of => :registry_date_event_employees
end

app/models/registry/department.rb
class Registry::Department < ApplicationRecord
	has_many :registry_municipalities, :class_name => "Registry::Municipality", 
		foreign_key: "registry_department_id", :inverse_of => :registry_department

	def display_name
		self.name
	end
	def self.security_name
		"Departamento"
	end
end

app/models/registry/employee.rb
class Registry::Employee < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	
	before_destroy :check_for_event

	before_save :check_for_coordinador
	
 	belongs_to :registry_employee_position, :class_name => "Registry::EmployeePosition", :inverse_of => :registry_employees

 	#belongs_to :boss, :class_name => "Registry::Employee"
 	belongs_to :registry_therapy_group, :class_name => "Registry::TherapyGroup", :inverse_of => :registry_employees

 	has_many :registry_events, :class_name => "Registry::Event", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

	has_many :registry_date_event_employees, :class_name => "Registry::DateEventEmployee", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

	has_one :registry_date_event, :through => :registry_date_event_employees, 
		:class_name=> "Registry::DateEvent", :inverse_of => :registry_employees

	has_many :registry_patient_assistances, :class_name => "Registry::PatientAssistance", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

	scope :employee, -> (employee) { where(:id => employee)}
  	scope :employee_position, -> (employee_position) { where(:registry_employee_position => employee_position)}
  	scope :active, -> (active) { where(:active => active)}

	include Filterable

	include AvoidDestroyReferencesUtility 
	include PersonalData 
 	def self.security_name
		"Colaboradores"
	end
	
	def self.get_coordinadores
		Registry::Employee.where(:registry_employee_position_id => Registry::EmployeePosition.where(:name => "Coordinador").first.id)
	end

 	def start_date_formatted
		if !self.new_record?
			start_date.strftime("%d/%m/%Y")
		else
			start_date
		end
	end

	def display_name
		"#{first_name} #{last_name}"
	end

	validates_presence_of :start_date, :registry_employee_position_id, :registry_therapy_group_id

	private
	def check_for_event
		check_for_relation(registry_events, "Evento")
	end
	def check_for_coordinador#(selfPostitionChanged=false)
		employee_therapy_group_related = Registry::Employee.where(:registry_therapy_group_id => self.registry_therapy_group_id, 
				:registry_employee_position_id => Registry::EmployeePosition.where(:name => "Coordinador").first.id)
		if self.registry_employee_position.name == "Coordinador"
			self_employee_relation = employee_therapy_group_related.where(:id => self.id) if self.id.present? 
			if employee_therapy_group_related.present? && self_employee_relation.blank?
				errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} ya posee un coordinador asociado.")
			end	
		else
			if employee_therapy_group_related.present?
				employee_record = employee_therapy_group_related.where(:id => self.id)
				if employee_record.present? 
					if Registry::Employee.where(:registry_therapy_group_id => self.registry_therapy_group_id, :boss_id => self.id).present?
						errors.add(:base,"El colaborador a modificar es coordinador de el grupo de terapia #{self.registry_therapy_group.display_name}. Existen colaboradores a su cargo, modifique los colaboradores asociados")
					else
						errors.add(:base,"El colaborador a modificar es coordinador de el grupo de terapia #{self.registry_therapy_group.display_name}. Debe existir un coordinador para el grupo de terapia")
					end
				else
					errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} tiene un coordinador asociado, seleccione el coordinador para poder proceder.") if self.boss_id.blank?
				end
			else
				errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} NO tiene un coordinador asociado, cree el coordinador para poder proceder.")
			end
		end
		if self.errors.present?
			raise CustomExceptions::SpecialException
		end
	end
end

app/models/registry/employee_position.rb
class Registry::EmployeePosition < ApplicationRecord
	before_destroy :check_for_employee

	has_many :registry_employees, :class_name => "Registry::Employee", 
		foreign_key: "registry_employee_position_id", :inverse_of => :registry_employee_position

	include AvoidDestroyReferencesUtility 

	def display_name
		name
	end

	validates_presence_of :name, :description
	def self.security_name
		"Cargo"
	end

	private
	def check_for_employee
		check_for_relation(registry_employees, "Colaborador")
	end

end

app/models/registry/event.rb
class Registry::Event < ApplicationRecord
	belongs_to :registry_therapy_group, :class_name => "Registry::TherapyGroup", :inverse_of => :registry_events
	belongs_to :registry_therapy_room, :class_name => "Registry::TherapyRoom", :inverse_of => :registry_events
	belongs_to :registry_employee, :class_name => "Registry::Employee", :inverse_of => :registry_events

	has_many :registry_event_patients, :class_name => "Registry::EventPatient", :dependent => :destroy,
		foreign_key: "registry_event_id", :inverse_of => :registry_event
	
	has_many :registry_patients, :through => :registry_event_patients, :class_name => "Registry::Patient"

	accepts_nested_attributes_for :registry_event_patients,
		:allow_destroy => true,
		:reject_if     => :all_blank

	scope :patient, -> (patient) { joins(:registry_event_patients).where(:"registry_event_patients.registry_patient_id" => patient)}
	scope :employee, -> (employee) { where(:registry_employee => employee)}
	scope :therapy_room, -> (room) { where(:registry_therapy_room => room)}
	scope :therapy_group, -> (group) { where(:registry_therapy_group => group)}


	scope :scoped_events, -> (record) {
		where("registry_events.id <> ?",record.id) if !record.new_record? 
	}

	
	include Filterable
	include ActiveModel::Validations

  	validates_with Validator::EventValidator
	
	validates_presence_of :registry_employee_id, :registry_therapy_room_id, :registry_event_patient_ids

	validates :end_time, date: {on_or_after: :start_time}

	serialize :recurring, Hash
	attr_accessor :dummy_start_time
	before_validation :mark_registry_event_patient_for_destruction
	
	def self.security_name
		"Agenda"
	end

	def mark_registry_event_patient_for_destruction
		registry_event_patients.each do |registry_event_patient|
			if registry_event_patient.registry_patient.blank?
				registry_event_patient.mark_for_destruction
			end
		end
	end

	def display_name
		name
	end

	def start_time_formatted
		if !self.new_record? || self.start_time.present?
			start_time.strftime("%d/%m/%Y %T")
		else
			start_time
		end
	end
	def end_time_formatted
		if end_time.present?
			if !self.new_record? || self.end_time.present?
				end_time.strftime("%d/%m/%Y")
			else
				end_time
			end
		else
			end_time = Date.today.strftime("%d/%m/%Y")
		end
	end
	def recurring=(value)
		if RecurringSelect.is_valid_rule?(value)
			super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
		else
			super(nil)
		end
	end
	def rule
		IceCube::Rule.from_hash recurring
	end
	def schedule(start)
		schedule = IceCube::Schedule.new(start)
		schedule.add_recurrence_rule(rule)
		schedule
	end
	def calendar_events(start, custom_end_date = nil)
		if recurring.empty?
			self.dummy_start_time = start_time
			[self]
		else
			start_date = start
			if self.end_time.present?
				self.end_time = self.end_time + 1.day 
			end
			if custom_end_date.present?
				end_date = custom_end_date
			else
				end_date = self.end_time || start_date
			end
			schedule(start_date).occurrences(end_date).map do |date|
				Registry::Event.new(id:id, name:name, registry_employee_id: registry_employee_id, 
					registry_patient_ids: registry_patient_ids, registry_therapy_room_id: registry_therapy_room_id,
					start_time:date.change(:hour => start_time.hour), dummy_start_time:start_time)
			end
		end
	end
	def self.date_range(start_date)
		beginning = start_date.beginning_of_week
		ending    = start_date.end_of_week
		(beginning..ending).to_a
    end
	def simple_calendar_events_array(start)
		if recurring.empty?
			[{date_start_time:start_time.strftime("%d/%m/%Y"), hour_start_time:start_time.hour}]
		else
			start_date = start_time
			if end_time.present?
				end_date = end_time + 1.day 
			else
				end_date = start_date
			end
			schedule(start_date).occurrences(end_date).map do |date|
				{date_start_time:date.strftime("%d/%m/%Y"), hour_start_time:date.hour}
			end
		end
	end
end

app/models/registry/event_patient.rb
class Registry::EventPatient < ApplicationRecord
  belongs_to :registry_event, :class_name => "Registry::Event", :inverse_of => :registry_event_patients
  belongs_to :registry_patient, :class_name => "Registry::Patient", :inverse_of => :registry_event_patients

  	def self.security_name
		"Agenda de Paciente"
	end
end

app/models/registry/level.rb
class Registry::Level < ApplicationRecord
	before_destroy :check_for_therapy_room

	belongs_to :registry_age_range, :class_name => "Registry::AgeRange", :inverse_of => :registry_levels

	has_many :registry_therapy_rooms, :class_name => "Registry::TherapyRoom", 
		foreign_key: "registry_level_id", :inverse_of => :registry_level
  	
  	include AvoidDestroyReferencesUtility 

  	def display_name
		name
	end

	def self.security_name
		"Áreas"
	end
  	
  	validates_presence_of :name, :description, :registry_age_range_id

  	private
	def check_for_therapy_room
		check_for_relation(registry_therapy_rooms, "Salón")
	end
end

app/models/registry/medical_record.rb
class Registry::MedicalRecord < ApplicationRecord
  belongs_to :registry_patient, :class_name => "Registry::Patient", :inverse_of => :registry_medical_records
  belongs_to :registry_therapy_type, :class_name => "Registry::TherapyType", :inverse_of => :registry_medical_records

  	def self.security_name
		"Ficha Clínica"
	end
end

app/models/registry/municipality.rb
class Registry::Municipality < ApplicationRecord
  belongs_to :registry_department, :class_name => "Registry::Department", :inverse_of => :registry_municipalities
  def display_name
  	self.name
  end
  def self.security_name
	"Municipio"
  end
end

app/views/registry/therapy_groups/_form.html.erb
<%= form_for(registry_therapy_group, html: {:class=>"form-horizontal form-label-left", :novalidate => nil}) do |f| %>
  <% if registry_therapy_group.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= registry_therapy_group.errors.count %> error(es) <%=t 'activerecord.errors.template.header.other', :model => 
        t("will_paginate.models.registry_therapy_group.one")%></h2>

      <ul>
      <% registry_therapy_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :name, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Nombre <span class="required">*
    <%end%> 
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, :class=>"form-control col-md-7 col-xs-12",:required=>"required" %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :description, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do %>
    Descripción <span class="required">*
    <%end%> 
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :description, :class=>"form-control col-md-7 col-xs-12",:required=>"required" %>
    </div>
  </div>

  <div class="tab-pane">
    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">Salones <span class="required">*</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= select_tag 'registry_therapy_group[registry_therapy_group_rooms_attributes][registry_therapy_room_ids]',
        options_from_collection_for_select(Registry::TherapyRoom.all, "id", "display_name", @selected_therapy_room),
        {:multiple => true, :size =>10, :class=>"select2_multiple form-control",:required=>"required"}
        %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%=link_to("Cancelar", registry_therapy_groups_path, :class=>"btn btn-primary")%>
      <button id="send" type="submit" class="btn btn-success">Guardar</button>
    </div>
  </div>
<% end %>

app/views/registry/therapy_groups/edit.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="title_page">
	      Terapias
	    </div>
		<div class="x_title">
			<h2>Editar Grupo de Terapia: (<%=@registry_therapy_group.display_name%>)</h2>
			<div class="clearfix"></div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_content">
						<%= render 'form', registry_therapy_group: @registry_therapy_group %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/registry/therapy_groups/index.html.erb
<div class="right_col" role="main">
  <div class="">

    <div class="clearfix"></div>
    <div class="title_page">
        Terapias
      </div>
    <div class="x_title">
      <h2>Grupos de Terapia</h2>
      <ul class="nav navbar-right panel_toolbox panel_button">
        <li>
          <%= link_to(new_resource_icon,new_registry_therapy_group_path, :"data-toggle"=>"tooltip", :"data-placement"=>"top", :title=>"", :rel=>"nofollow", :"data-original-title"=>"Nuevo", :class=> "plus_header_container")%>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <% if notice.present?%>
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <%= notice %>
      </div>
    <% end %>
    <div class="row">

      <div class="clearfix"></div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

          <div class="x_content">
            
            <div class="table-responsive">
              <div class="digg_pagination">
                <div class="pagination_pages">
                  <%= will_paginate @registry_therapy_groups, :container => false %>
                </div>
                <div class="page_info">
                  <%= page_entries_info @registry_therapy_groups, :model => "registry_therapy_group" %>
                </div>
              </div>
              <%= form_tag destroy_multiple_registry_therapy_groups_path, method: :delete, data: { confirm: "Are you sure?"}, :class=>"multi_delete_form" do %>
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th>
                        <input type="checkbox" id="check-all" class="flat">
                      </th>
                      <th class="column-title">Nombre</th>
                      <th class="column-title">Salones en este grupo</th>
                      <th class="column-title no-link last text-center" colspan="3">Action</th>
                      </th>
                      <th class="bulk-actions" colspan="7">
                        <a type="button" id="delete_records" class="antoo submit-form" style="color:#fff; font-weight:500; cursor:pointer">Eliminar ( <span class="action-cnt"> </span> ) <%=delete_resource_icon%></i></button>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @registry_therapy_groups.each_with_index do |registry_therapy_group, index| %>
                      <tr class="<%= index.odd? ? 'odd' : 'even'%> pointer">
                        <td class="center">
                                    <input type="checkbox" name="registry_therapy_group_ids[]" id="registry_therapy_group_id_<%=registry_therapy_group.id%>" value="<%=registry_therapy_group.id%>" class="flat deletable">
                              </td>

                        <td><%= registry_therapy_group.name %></td>
                        <td><%= registry_therapy_group.registry_therapy_rooms.count %></td>
                        <td class="split_left_icon_section last text-center"><%= link_to show_resource_icon, registry_therapy_group %></td>
                        <td class="last text-center"><%= link_to edit_resource_icon, edit_registry_therapy_group_path(registry_therapy_group) %></td>
                        <td class="last text-center"><%= link_to delete_resource_icon, registry_therapy_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/registry/therapy_groups/new.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="title_page">
	      Terapias
	    </div>
		<div class="x_title">
			<h2>Nuevo Grupo de Terapia</h2>
			<div class="clearfix"></div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					
					<div class="x_content">
						<%= render 'form', registry_therapy_group: @registry_therapy_group %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/registry/therapy_groups/show.html.erb
<div class="right_col" role="main" style="min-height: 1053px;">
  <div class="">
    <div class="clearfix"></div>
    <div class="title_page">
        Terapias
      </div>
    <div class="x_title">
      <h2><%=@registry_therapy_group.display_name %></h2>
      <div class="clearfix"></div>
    </div>
    <% if notice.present?%>
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <%= notice %>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-12">

        <div class="x_panel">

          <div class="x_content">
            
            <div class="col-md-8 col-lg-8 col-sm-7">
              <!-- blockquote -->
              <blockquote>

                <h2>Nombre:</h2>
                <h4><%= @registry_therapy_group.display_name %></h4>

                <h2>Descripción:</h2>
                <h4><%= @registry_therapy_group.description %></h4>
                
              </blockquote>

              <blockquote class="blockquote-reverse">

                  <%= link_to 'Editar', edit_registry_therapy_group_path(@registry_therapy_group), :class=>"btn btn-primary" %>
                  <%= link_to 'Atrás', registry_therapy_groups_path, :class=>"btn btn-success" %>

              </blockquote>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>